# 애플리케이션 이름
spring.application.name=SweetScoopBack

server.port=8888

# ==========================
# MySQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3307/sweetscoop?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin
#spring.datasource.password=admin

# UTF-8 Response ì¤ì 
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# ==========================
# MyBatis
# ==========================
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.sweetscoop.order.model


# SQL ë¡ê·¸
logging.level.com.sweetscoop=DEBUG

# ì»¬ë¼ëª(snake_case) â ë³ìëª(camelCase) ìë ë³í
mybatis.configuration.map-underscore-to-camel-case=true


toss.payment.secret-key=test_sk_DpexMgkW36vBRZQPEjKd3GbR5ozO

#JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ==========================
# JPA / Hibernate 
# ==========================

logging.level.order.repository=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE