# 애플리케이션 이름
spring.application.name=SweetScoopBack

# 서버 포트
server.port=8888

# ==========================
# MySQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3307/sweetscoop?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin

# UTF-8 Response 설정
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# ==========================
# MyBatis
# ==========================
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.sweetscoop.order.model


# SQL 로그
logging.level.com.sweetscoop=DEBUG

# 컬럼명(snake_case) → 변수명(camelCase) 자동 변환
mybatis.configuration.map-underscore-to-camel-case=true

# SQL 로그 출력(선택)
logging.level.order.repository=DEBUG

toss.payment.secret-key=test_sk_DpexMgkW36vBRZQPEjKd3GbR5ozO
